if (VegaFEM_BUILD_MODEL_REDUCTION)
  add_subdirectory(largeModalDeformationFactory)
  if (VegaFEM_ENABLE_OpenGL_SUPPORT)
    add_subdirectory(reducedDynamicSolver-rt)
  endif()
endif()
if (VegaFEM_ENABLE_OpenGL_SUPPORT)
  add_subdirectory(displayObj)
  add_subdirectory(interactiveDeformableSimulator)
endif()
if (VegaFEM_BUILD_WEB_DEMO)
  add_subdirectory(web)
endif()
add_subdirectory(volumetricMeshUtilities)
